# avosoft_retail/avosoft_engine/io/base.py

from typing import Protocol, Iterable, Mapping

class Writer(Protocol):
    def write_jsonl(self, path: str, records: Iterable[Mapping]): ...
    def write_csv(self, path: str, rows: Iterable[Mapping], header: list[str]): ...

class DBWriter(Protocol):
    def bulk_insert(self, table: str, rows: list[tuple], columns: list[str]): ...
    def commit_close(self, ok: bool = True): ...
